### ISSUE TITLE
2016 Update?

### ISSUE THREAD

**Issue by matt3224** [ryanmorr/query#2]
Hey man,

Has this changed in the 2 years since you wrote it. I'm in the somewhat glorious position of only needing to support IE11+ and the last 2 versions of all the other browsers.

Would you recommend any changes to your query function?

Thanks,

**Comment by ryanmorr** [comment]
@matt3224 The query function is so simple, it's future proof, so no updates are necessary. You may want to check out my other project [sonic](https://github.com/ryanmorr/sonic) which is a context-aware and extentable CSS selector engine built on top of the native functions, similar to query.
