### ISSUE TITLE
query looks css selector compatible

### ISSUE THREAD

**Issue by pwFoo** [ryanmorr/query#3]
The query function looks compatible to [css selectors](http://www.w3schools.com/cssref/css_selectors.asp), right?

```
query('#section1 > div');
query('#section1 + .myclass');
```

Tested the regexp with some examples
http://www.regexpal.com/?fam=96821

Nice and small function! 👍

**Comment by ryanmorr** [comment]
Yes, the query function is compatible with all CSS selectors.
